//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;

namespace ConsomiTounsiFront.Models
{
    public partial class consomitounsiEntities : DbContext
    {
        public consomitounsiEntities()
            : base("name=consomitounsiEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

       public virtual DbSet<delivery> delivery { get; set; }
           public virtual DbSet<exchange> exchange { get; set; }
        public virtual DbSet<reclamation> reclamation { get; set; }
        public virtual DbSet<remboursement> remboursement { get; set; }
        public virtual DbSet<reparation> reparation { get; set; }
        public virtual DbSet<subject> subject { get; set; }
         }
}