//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsomiTounsiFront.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.command = new HashSet<command>();
        }
    
        public int id { get; set; }
        public string adresse { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public float frais { get; set; }
        public float poids { get; set; }
        public bool state { get; set; }
        public Nullable<int> deliver_men_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<command> command { get; set; }
        //public virtual delivery_men delivery_men { get; set; }
        public virtual User user { get; set; }
    }
}
