//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsomiTounsiFront.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class payment
    {
        [Key]
        public long payment_id { get; set; }

        [DataType(DataType.Date)]
        public DateTime payment_date { get; set; }
        //public string payment_delivery_type { get; set; }
        public string payment_type { get; set; }
        public float total_price { get; set; }
        [ForeignKey("bill_bill_id")]
        public Nullable<long> bill_bill_id { get; set; }
    
        public virtual bill bill { get; set; }
    }
}
